---
- name: Install fcserver
  git:
    repo: https://github.com/scanlime/fadecandy.git
    dest: "{{ fadecandy_install_dir }}"
- name: Install systemd service
  template:
    src: fadecandy.service.j2
    dest: /etc/systemd/system/fadecandy.service
    mode: 0644
    owner: root
    group: root
- name: enable systemd service
  systemd:
    name: fadecandy
    daemon_reload: yes
    enabled: yes
    state: started
- name: fadecandy config
  template:
    src: default.json.j2
    dest: /etc/fadecandy.json
