---
- name: Install fcserver
  git:
    repo: https://github.com/scanlime/fadecandy.git
    dest: "{{ fadecandy_install_dir }}"
- name: Install systemd service
  template:
    src: fadecandy.service.j2
    dest: /etc/systemd/system/fadecandy.service
    mode: 0644
    owner: root
    group: root
  register: fadecandy_service
- name: enable systemd service
  systemd:
    name: fadecandy
    daemon_reload: yes
    enabled: yes
    state: started
- name: fadecandy config
  template:
    src: fadecandy.json.j2
    dest: "{{ fadecandy_config_file_path }}"
  register: fadecandy_config
- name: restart service
  systemd:
    name: fadecandy
    state: restarted
  when: fadecandy_config.changed or fadecandy_service.changed
