---
- name: update and deploy
  block:
    - include_tasks: deploy.yml
  become_user: "{{ awakening_lights_install_user }}"

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: nginx started and enabled
  systemd:
    name: nginx
    state: started
    enabled: true

- name: install lights.local nginx conf to serve react app
  template:
    src: lights.local.j2
    dest: /etc/nginx/sites-enabled/lights.local
  register: lights_local_conf

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  when: lights_local_conf.changed
